travis:
  secure:
    BINSTAR_TOKEN: Or7KNe5/z7kdprsixqi+DRvU7MnEl6M5DhztTN+NPpWuRk+GoFtXITfyhJto3xMQhlg+UwgObCUhkT7wIlEs0wQ7WFazvcQ0ghwleFhNksMCIbiCxcLjz+rBh2m2lFPi6VswSU2nZaJ6x9o8+Ko40Bv3P/yM83mRhZCMIXV1ry17VRTwSl0lBPxeIKu2hwe7WVNbp7vT4FcaAW0oMcW6iLqqATE73KWd2L1Ilh9OLaO4dSPDEiBHFHGIcVCcd0y2w10A0wBvy4wqqAPU1t+AFferG1Un0IKib5QmqFcCdQxmCrVrUlbHZcWIdaYBmISQWkUBO980uWRrB48fDfE2Dbor6LxQ5FbGGUZDCL9rBH5you6b57+sD+FQVu0sTerTu20K6IShNIr7DlBIPVWWc8rL4EvnOrknQSanf48SYdnDOhvKvb9K9ddT52lOFVDQwp4EVG1iAQQvRH/L33brIDRfgApsCQFZZYb2c1vvyC7MLU6jL0qtFg7/ucvNJlBeGzRYezkJk1UfbiRalyULeRWNJT2huB1ZCzQ2H6FbfuJTaaqIBtrAP5CGTCfJGK3ddU3PfLM9Byqgc20grpKFDOPrvL9x6Vpkxe4yEGd2pw5dttk/VZB1HGxM1hPdlzspQtbz4urrapYlL8zVrGBktn55LFzlAae9bmbgQTPXY7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
