travis:
  secure:
    BINSTAR_TOKEN: g7CYGSqYdYRpJP8rYvkcgoaKpSiDxQOwEo6XNVxss62BfshBWp/MvLZfxDlwA1PsC5eqUFogXRr/E2oGpuEmDxSUXIF7c34e96CfYvZaio/cOHQJoVue/raUI4iMkET09CAlnw7EWkcyB7Twbbu3mXYRNFCI/TvuZL7jZoOvFO08NUDJr404xitBzmbFw3O453PujIngV1Ds+HPxXpVdXvLRvs0Sxof4ZYIKbOCexyf/5l93U9lax/4Our8cDJWs0A2FKmWn0Kwc8IKZPQjG0Hx5WOZJx9DxaeaQZ4xv1kamhlNAcYsZjWn4hLDFoA9guroolmYALeLHdrqsbW7edYQlfdYwXpP4rjykIaWqcKdjd4YcyPKs0TM4EQcCdOBP+3Ep+k8CZr8WKv0y+9XhGmc00LyeEQMJVC+RqY7DEPydtDdWmBJS3rZs73AbXyHCPOf36shNpwFSAfBlBlRQDfxzgJxwwa0AeBPfyLGOOQnr6dIyfkECehFuu4iGeuhcaNzBysgltqbxtuFFw1tjc7PS9VqPTNvxQY5Y13yRVCvV03i8+24varnceedDsCL8qD2dRYfpy0eQE5aZgbBLfVuZtVAh6JMh8dvAHL1KZ1TlphAoPIadAnZP6e7Yr9n9x21u1/TZQC2yppU7CM7677ZfAB9ki6ViuB36hccxPug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
